### ISSUE TITLE
HELPrct vs HELPmiss

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaicData#10]
I had thought that `HELPrct` had only complete cases and that `HELPmiss` was an expanded version that included missing data.  But I'm seeing this:

``` r
tally( ~complete.cases(HELPrct))
## 
##  TRUE FALSE 
##   117   336 
tally( ~complete.cases(HELPmiss))
## 
##  TRUE FALSE 
##   117   353 
```

The help currently says:

> This dataset is a subset of the HELPmiss data which includes an additional 17 subjects with partially observed data on some of the baseline variables. 

At a minimum we should clarify that there is already some missing data in `HELPrct`, or perhaps we should remove either some rows or columns so that there is no missing data.

Thoughts?

**Comment by rpruim** [comment]
In case you are wondering where the missingness is:

``` r
dfapply( HELPrct, function(x) sum(is.na(x)))
##          age anysubstatus         cesd           d1   daysanysub     dayslink     drugrisk 
##            0          207            0            0          209           22            1 
##          e2b       female           i1           i2           id       indtot   linkstatus 
##          239            0            0            0            0            0           22 
##          mcs          pcs       pss_fr      sexrisk 
##            0            0            0            0 
```

**Comment by nicholasjhorton** [comment]
The HELPrct sample is the set included in the randomized trial paper.  Perhaps it would be best to state that these n=453 subjects were fully observed on the age, cesd, d1, female, i1, i2, indtot, mcs, pcs, pss_fr and sexrisk variables.  

I don't recall how to change documentation in Roxygen, nor am I set up to check the package afterwards so I'd ask if you could add a note along these lines into the HELPrct docs.

**Comment by rpruim** [comment]
Here's the new documentation:

> This data set is a subset of the HELPmiss data set restricted to the 453 subjects who were fully observed on the age, cesd, d1, female, sex, g1b, homeless, i1, i2, indtot, mcs, pcs, pss_fr, racegrp, satreat, substance, treat, and sexrisk variables. (There is some missingness in the other variables.) HELPmiss contains 17 additional subjects with partially observed data on some of these baseline variables. This is also a subset of the HELPfull data which includes 5 timepoints and many additional variables.
