### ISSUE TITLE
add fusion1 and fusion2 from the old fastR

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaicData#14]

**Comment by rpruim** [comment]
A new `fastR` package was submitted to CRAN and the maintainer change didn't get spotted by the CRAN folks.  They are working to restore my `fastR` to CRAN.  Once it returns, the data sets should again be available.

Note:  `fastR2` is coming soon and we should use the new data sets there (with some renaming) once it is on CRAN.
