### ISSUE TITLE
units on Alcohol

### ISSUE THREAD

**Issue by beanumber** [ProjectMOSAIC/mosaicData#17]
What are the units on alcohol consumption in `Alcohol`? Litres per person per year??

Also, there is a bogus link to the rail trail information in the documentation.

**Comment by rpruim** [comment]
Danny, Nick,

Which of you found and added this data?  Looks the claim is that it is from gapminder, so presumably we should be able to find it again, update the code book to include units, and give a correct reference to the source page on gapminder.

**Comment by beanumber** [comment]
I assume this is the link: (https://spreadsheets.google.com/pub?key=0AgogXXPMARyldGJqTDRfNHBWODJMRWlZaVhNclhNZXc&gid=0)

**Comment by nicholasjhorton** [comment]
I'd suggest https://www.gapminder.org/data/ as a link.  I don't know how the railtrail link was added.

Here's a description of the alcohol measure:

Recorded and estimated average alcohol consumption, adult (15+) per capita consumption in litres pure alcohol

**Comment by rpruim** [comment]
done.
