### ISSUE TITLE
fix error in documentation of H14

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaicData#19]
coded as substance (not 0-10)
![screen shot 2016-12-09 at 7 11 07 am](https://cloud.githubusercontent.com/assets/530542/21048764/f4a79b70-bdde-11e6-9763-f6383647fe1e.png)

**Comment by rpruim** [comment]
@nicholasjhorton, has this been dealt with?

**Comment by nicholasjhorton** [comment]
Alas, no.  What's your timetable for release?

**Comment by rpruim** [comment]
I'm pretty much ready to release to CRAN.  This is blocking submission of `ggformula` which CRAN has requested due to the disappearance of `weatherData`.  But I can hold off if this is an easy thing to take care of.

**Comment by nicholasjhorton** [comment]
Fixed via https://github.com/ProjectMOSAIC/mosaicData/commit/78fe746f060e2ee744f2edd8d705ea0971dcc34a.  Sorry for the atrocious delay.
