### ISSUE TITLE
add renamed versions of i1 and i2 in HELPrct

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaicData#21]
Perhaps others need better names too

**Comment by nicholasjhorton** [comment]
I'm not seeing these: have you pushed these changes?

Thanks in advance for any guidance,

Nick

**Comment by rpruim** [comment]
I haven't done it yet.  It's a open issue.  It comes to mind each time I use this data set for a Less Volume talk, but I never get around to doing something about it.  So this time I'm creating an issue in hopes that that will make it get done.  Feel free to do it yourself if you like.

I think we should keep the old variables (redundantly) for backward compatibility.

**Comment by nicholasjhorton** [comment]
How about adding the following copies of the variables:

avgnumdrinks --> • i1 average number of drinks (standard units) consumed per day, in the past 30 days (measured at baseline)

maxnumdrinks -->	• i2 maximum number of drinks (standard units) consumed per day, in the past 30 days (measured at baseline)


> On May 12, 2017, at 10:04 AM, Randall Pruim <notifications@github.com> wrote:
> 
> I haven't done it yet. It's a open issue. It comes to mind each time I use this data set for a Less Volume talk, but I never get around to doing something about it. So this time I'm creating an issue in hopes that that will make it get done. Feel free to do it yourself if you like.
> 
> I think we should keep the old variables (redundantly) for backward compatibility.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Comment by rpruim** [comment]
I just added `max_drinks` and `avg_drinks`.
