### ISSUE TITLE
HELPfull documentation includes a lot of unnecessary abbreviations

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaicData#23]
I'm assuming this was copied from some other document, but it might be hard from some readers and sets off all sorts of alarms in the spell-checker as part of package submission.

**Comment by rpruim** [comment]
`Amyphys/em prb intf w/ soc act-lst 4 wks` -- translation?

Perhaps: Any physical or emotional problem interfere with social activity in last 4 weeks?

Does that seem reasonable?

**Comment by rpruim** [comment]
Stumpers:

```
#'     \item{\code{PHYS2}} {InDUC-2L-Physical 9Raw (w/o M48)}
#'     \item{\code{PHYS}} {InDUC-2L-Physical-Raw}
```

**Comment by nicholasjhorton** [comment]
Fixed via https://github.com/ProjectMOSAIC/mosaicData/commit/78fe746f060e2ee744f2edd8d705ea0971dcc34a
