### ISSUE TITLE
Remove broken link

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaicData#24]
```
Found the following (possibly) invalid URLs:
  URL: http://www.math.smith.edu/help
```

I've commented this out for now.  If there is an updated reference, we can add it back.

**Comment by rpruim** [comment]
Also this one:
```
See also \url{http://www.math.umt.edu/patterson/ProfileLikelihoodCI.pdf}.
```

**Comment by nicholasjhorton** [comment]
Here's the corrected link: https://nhorton.people.amherst.edu/help/

Sorry that I didn't update mosaicData with this info when I made the switch.



> On Jan 23, 2018, at 7:28 PM, Randall Pruim <notifications@github.com> wrote:
> 
> Found the following (possibly) invalid URLs:
>   URL: http://www.math.smith.edu/help
> 
> I've commented this out for now. If there is an updated reference, we can add it back.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000
