### ISSUE TITLE
add SET (statistical education of teachers) datasets

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaicData#3]

**Comment by rpruim** [comment]
Perhaps I'll talk with Chris Franklin about this.

**Comment by rpruim** [comment]
I wonder if it would be better to have a `SETdata` package that the SET folks are responsible for.  We could consult with them about turning it into a package.

**Comment by nicholasjhorton** [comment]
I'm halfway through the report, and I've only found one dataset.  So it might feel like overkill.

**Comment by rpruim** [comment]
If there is only a small number it makes more sense for use to put them in `mosaicData`.  I was thinking they were curating a collection.  I'll see what Chris Franklin knows.
