### ISSUE TITLE
Release 0.18

### ISSUE THREAD

**Issue by romainfrancois** [ProjectMOSAIC/mosaicData#32]
Do you have a plan to release to CRAN ?

It looks like this commit: https://github.com/ProjectMOSAIC/mosaicData/commit/4247c74cc2f18dee07e9faa0c5b6cbed4b203789 has fixed an issue that makes other packages (e.g. `ggformula`) fail against the upcoming (in a few days) release of dplyr 1.0.0.

**Comment by rpruim** [comment]
I'm hoping too.  We are in the last week of our semester, so the timing is not convenient.  Just need to find time to go through all of the CRAN checking hoops.

**Comment by rpruim** [comment]
@romainfrancois: prepping for CRAN release now.  Hope to submit later this evening pending the usual checks.

**Comment by rpruim** [comment]
On CRAN now.
