### ISSUE TITLE
looking for pkgdown site

### ISSUE THREAD

**Issue by homerhanumat** [ProjectMOSAIC/mosaicData#38]
[http://projectmosaic.github.io/mosaicData](http://projectmosaic.github.io/mosaicData) redirects to http://www.mosaic-web.org/mosaicData, with 404 error.

**Comment by rpruim** [comment]
Looks like there was a bad setting under pages for this repo.

I've fixed that (and rebuilt the pkgdown site based on the new version that went to CRAN earlier this week).  

@homerhanumat, let us know if you still have issues.

**Comment by nicholasjhorton** [comment]
@rpruim thanks as always for your efforts and to @homerhanumat for pointing out the problem.

**Comment by homerhanumat** [comment]
Well, thanks as always for making and maintaining this!  Two final suggestions:

* on the mosaicData repo, link to the pkgdown documentation;
* on mosaic-web, make an active link to that documentation.

**Comment by rpruim** [comment]
I've put a link on the repo README.  @dtkaplan, are you the one currently maintaining mosaic-web?

**Comment by dtkaplan** [comment]
Yes, that’s me. I’ve put it on my to-do list.

**Comment by dtkaplan** [comment]
I've updated the link to the `{mosaicData}` pkgdown site and made a few other updates. On the "books" page, I've promoted your "remix" of *Statistical Modeling*. I note that in the preface to your remix, you mention a hoped-for completion by 2022. Maybe there is an update?
