### ISSUE TITLE
add SaratogaHouses dataset

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaicData#4]
Danny, if you can send me the data and codebook for this, I can put it together for the next mosaicData release (if there's interest).

**Comment by nicholasjhorton** [comment]
I'll ask Dick for this.

**Comment by rpruim** [comment]
Any progress on this?

**Comment by rpruim** [comment]
A first draft of this data set is now in the package.  We can open a new issues if we want to modify it.
