### ISSUE TITLE
clean up RailTrails data set

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaicData#7]
Things to do:
- add `season` variable with three levels
- make factor version of weekday variable (perhaps `day` with levels `weekday` and `weekend`)
- leave current 0/1 indicators there for backward compatibility

**Comment by rpruim** [comment]
Perhaps also add a richer version (`RailTrail2`) with finer data resolution (date, holiday or not, etc.)

**Comment by nicholasjhorton** [comment]
That's a good idea: I'll try to make it happen (but it will need to wait for a release in November or later).

**Comment by rpruim** [comment]
Danny and I created a data frame called Riders.  It's in the github repo.  Take a look at it to see whether you have suggestions for improvement.

``` r
head(Riders)
##         date       day highT lowT hi lo precip clouds riders  ct weekday wday
## 1 2005-04-05   Tuesday    62   39 62 39      0    0.8    236 236       Y    Y
## 2 2005-04-06 Wednesday    75   43 75 43      0    6.3    156 156       Y    Y
## 3 2005-04-07  Thursday    70   47 70 47      0    9.9    328 328       Y    Y
## 4 2005-04-08    Friday    65   48 65 48      0    7.2    418 418       Y    Y
## 5 2005-04-09  Saturday    66   38 66 38      0    0.0    629 629       N    N
## 6 2005-04-10    Sunday    74   33 74 33      0    2.5    635 635       N    N
```

The redundant variables are for the sake of the mosaic cheat sheet (to keep the code shorter).

**Comment by rpruim** [comment]
Unless there is some other data to add to this, I think it is ready to go.
