### ISSUE TITLE
Document the Riders data frame

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaicData#8]

**Comment by nicholasjhorton** [comment]
I've put the following together: is that helpful to move this forward?

[Riders.txt](https://github.com/ProjectMOSAIC/mosaicData/files/11202/Riders.txt)

**Comment by rpruim** [comment]
Thanks for the content.

Did you create this like it is or using roxygen?  I'd prefer to use roxygen for this.

**Comment by nicholasjhorton** [comment]
I created it as it is: I've not been using roxygen and figured it was better to get you the content than delay.

**Comment by rpruim** [comment]
I've converted this to roxygen and added it to the pacakge (beta branch for now).

Note: I've assumed that the precipitation is measured in inches and added that to the documentation.
