### ISSUE TITLE
add Dimes data set?

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaicData#9]
I've put the `Dimes` data set in for now.

**Comment by rpruim** [comment]
A colleague of mine has a data set with the mass and year of a sample of dimes

```
   Mass Year
1 2.259 2004
2 2.247 2004
3 2.254 1987
4 2.298 1988
5 2.287 1971
6 2.254 2007
```

I’d like to put this data set into either `mosaicData` or `fastR2` because I will used it as an example in the 2nd edition of my book.  (I use it as an example of propagation of uncertainty in the context of estimating with precision the number of dimes in the bag from the weight of the dimes in the bag, but I suppose it could be put to other uses as well.)

The question is whether we want it in `mosaicData`.

**Comment by nicholasjhorton** [comment]
I have no objection, but would really hope that there are other motivating examples that are, well, more motivating than the mass of dimes (it feels not dissimilar to number of chocolate chips or proportion of red M&M's to me).

Nick

**Comment by rpruim** [comment]
The primary example is to apply propagation of uncertainty to estimate (with precision estimates) the number of dimes in a large bag of dimes based on the mass of the dimes in the bag.  This sample can be used to determine how precisely we are estimating the mass of individual dimes.

Since year is there, one can also explore competing hypotheses about the mass of dimes over time:
- A: they get lighter because they material wears away
- B: they get heavier because the pick up grime

The data set comes from an actual application where junior high students collected dimes for a fundraiser and wanted to estimate the number of dimes they had before bringing them to the bank for official counting.

**Comment by nicholasjhorton** [comment]
That additional info is helpful.  I'd encourage you to submit this for JSE DSS if you have the time.

Just my $0.02,

Nick

> On Oct 24, 2015, at 12:31 PM, Randall Pruim notifications@github.com wrote:
> 
> The primary example is to apply propagation of uncertainty to estimate (with precision estimates) the number of dimes in a large bag of dimes based on the mass of the dimes in the bag. This sample can be used to determine how precisely we are estimating the mass of individual dimes.
> 
> Since year is there, one can also explore competing hypotheses about the mass of dimes over time:
> 
>   • A: they get lighter because they material wears away
>   • B: they get heavier because the pick up grime
> The data set comes from an actual application where junior high students collected dimes for a fundraiser and wanted to estimate the number of dimes they had before bringing them to the bank for official counting.
> 
> —
> Reply to this email directly or view it on GitHub.

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton
